export default function MatchExplanationBox({ explanation }) {
  return (
    <div className="bg-blue-50 border-l-4 border-blue-500 p-6 rounded relative h-full">
      <h3 className="text-xl font-bold mb-3 text-blue-900">Why this matches you</h3>
      <p className="text-gray-700 italic mb-4">"{explanation?.text || 'Explanation text generated by matching engine...'}"</p>
      
      <div className="mt-4">
        <h4 className="font-semibold text-sm text-gray-500 uppercase tracking-wide">Tag Alignment</h4>
        <div className="flex flex-wrap gap-2 mt-2">
          {explanation?.aligned_tags?.map((tag, i) => (
            <span key={i} className="px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full">{tag}</span>
          ))}
        </div>
      </div>
      
      {explanation?.neighborhood_alignment && (
        <div className="mt-4">
          <h4 className="font-semibold text-sm text-gray-500 uppercase tracking-wide">Neighborhood Vibe</h4>
          <p className="text-sm text-gray-700 mt-1">{explanation.neighborhood_alignment}</p>
        </div>
      )}
    </div>
  );
}
